FROM python:3.9.6

WORKDIR /usr/src/app

RUN python -m venv .venv
RUN . .venv/bin/activate
COPY requirements.txt ./
COPY requirements-tools.txt ./
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir wheel
RUN pip install --no-cache-dir -r requirements.txt && pip uninstall Jetson.GPIO
RUN pip install --no-cache-dir -r requirements-tools.txt
