target-version = "py311"

exclude = [
  ".venv",
  "display/waveshare_epd"
]

line-length = 120

[lint]
select = [
  "ALL"
]
ignore = [
	"ANN",		# flake8-annotations
	"ARG",		# flake8-unused-arguments
	"COM812",   # missing-trailing-comma
	"D",		# pydocstyle
	"ERA",		# eradicate
	"ISC001",   # single-line-implicit-string-concatenation
	"N",		# pep8-naming
	"RET504",   # unnecessary-assign
	"PLR0913",  # too-many-arguments
	"PLR2004",  # magic-value-comparison
	"TRY", 		# tryceratops
]

[lint.flake8-quotes]
inline-quotes = "single"

[format]
quote-style = "single"
